version: "3.7"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app-db"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
    restart: always
  app:
    image: golang:1.17-alpine
    restart: always
    ports:
      - "8080:80"
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["/bin/sh", "-c", "go build -o /app/app && /app/app production"]

